### ISSUE TITLE
Emulator drops out

### ISSUE THREAD

**Issue by kingvillain** [yifanlu/PSXperia#10]
I finally successfully generated my first game with this great tool, it installed no problems and icon shows as it should, however when I start the game it briefly shows "updating" then drops back out to droid menu again.

Used files from my Crash CRC3b6a23c1.

**Comment by yifanlu** [comment]
Can you send me the APK that you generated? Also, can you copy the Android logcat here?

**Comment by kingvillain** [comment]
I am struggling to work out how to get the logcat, here is the APK:
-removed-

**Comment by yifanlu** [comment]
I'm sorry I didn't see this before, but this is a duplicate of issue #4. This tool does not yet work with that version of Crash Bandicoot. Just keep a lookout on that issue post.
