### ISSUE TITLE
Icon not showing in Xperia Play Launcher (Playstation Pocket app)

### ISSUE THREAD

**Issue by woogers** [yifanlu/PSXperia#12]
I've got a new one.

Can you add the ability to set an icon for the apk to show in the Xperia Play Launcher (that launches on slide open; some call it the Pocket app, I think)? The default Android icon shows. Screenshot attached.

![Screenshot](http://woogers.net/apk/xpl.png)

**Comment by yifanlu** [comment]
It's actually the icon that you choose in the creator. 
![Screen](http://i.imgur.com/2jY3U.png)
Any 170x170 PNG file

**Comment by woogers** [comment]
My mistake, must have forgot to pick the icon this build around.

**Comment by sellh03** [comment]
Hi im using the NA Xperia Play r800x and i was wondering if there was a way to get that game launcher, the standard one included in my r800x wont show me any PS1 games including the pre installed Crash Bandicoot 1

**Comment by yifanlu** [comment]
Take a look at this: http://forum.xda-developers.com/showthread.php?t=1110405&page=3
