### ISSUE TITLE
Emulater crashes ingame (Game starts!)

### ISSUE THREAD

**Issue by muhski** [yifanlu/PSXperia#13]
Hi, here is my logcat :
http://pastebin.com/HjAk1Sfi

Game is Chrono Cross Disk 1
PSXperiaTool worked fine for me, APK installed fine, Game starts, but after the "Press Start" Screen the screen gets blue for 1 sec, then black, then close of the App!

BR
Muhski

**Comment by yifanlu** [comment]
Unfortunately, this is either due to the image you're using (not properly ripped), or the fact that sony's emulator does not work with it. I am trying to get a newer version of the emulator and that may solve the problem, but as of right now, there is nothing I can do about this. Sorry.

**Comment by muhski** [comment]
Ok!
I tried with different Images (.bin and .img) that I ripped seperatly...! Maybe I'll try it later with Syphon Filter.apk
