### ISSUE TITLE
Cannot get converter to work

### ISSUE THREAD

**Issue by TehH4rRy** [yifanlu/PSXperia#16]
Everytime I try to open the GUI It doesn't work. I click all the conditions, yes I have my xperia play yadadada. Then it does nothing. I am getting no errors or anything. Help me out? 

Happens when I try and open the .jar and the GUI script. running Ubuntu 11.04 btw.

**Comment by yifanlu** [comment]
I think you figured it out ;)

**Comment by TehH4rRy** [comment]
I didn't I closed it because I thought i figured it out. Any ideas?

**Comment by yifanlu** [comment]
You didn't figure it out? One hint: read carefully
;)

**Comment by TehH4rRy** [comment]
Downloaded the package, downloaded what i think is the binaries (source?) and extracted it into the folder that the psxperia.jar is in

**Comment by yifanlu** [comment]
I'm confident you'll figure it out.

**Comment by TehH4rRy** [comment]
Nope! I found a youtube video, says I need a file in system path directory. AAPK? I think something like that.

**Comment by TehH4rRy** [comment]
Sigh, I am fucking idiot

**Comment by TravisTravis222** [comment]
lol
