### ISSUE TITLE
Display Issue & Sound Issue

### ISSUE THREAD

**Issue by Alpha-9000** [yifanlu/PSXperia#17]
I build the Apk & ZPAK files for SRW Alpha also Getter Robot the Great Battle & it installs but when I play it run's fine but when the Battle Animation Starts, half of the animation displays & sometime the voice's cut off.
What am I doing wrong ?

**Comment by yifanlu** [comment]
Sorry, but I cannot help game Bugs as the emulator is coded by Sony. Only they can fix it.
