### ISSUE TITLE
Graphic Glitches

### ISSUE THREAD

**Issue by ookees** [yifanlu/PSXperia#18]
I have tried two games so far Mega Man X 4 and 5 both games play but with graphic glitches. As soon as the character moves on screen the glitch occurs. Everything else seems to work, sound, controls, etc. I will try other games when I get a chance.

Never mind I see you cant comment on game issues just the tool itself. The tool works great.

**Comment by yifanlu** [comment]
Feel free to modify this page: https://github.com/yifanlu/PSXperia/wiki/Compatibility
