### ISSUE TITLE
Sound and graphic issues

### ISSUE THREAD

**Issue by laloevil10** [yifanlu/PSXperia#19]
Hi there, first and foremost congratulations and a thousand thank yous for your great emulation work, I have been testing PSXperia for a while now and I have noticed some issues with sound and graphics on some games, for  example, I own both a copy of Metal Gear Solid and Castlevania Symphony of the night, with MGS I have noted that there is no sound at all and the game crashes completely after choosing the difficulty; on Castlevania some of the rendering is completely black (characters and breakable/usable objects). I haven't teseted more games yet but it does a perfect job with games like FF7 or Star Ocean.

I have analysed the so called "preferences.xml" file on the ucc folder of each game and I see that a lot of the features on the emulator look pretty similar to the settings available in FPSE and I've been trying to play around with the PLAY's emulator itself instead of changin the pref file and I guess my point is that if somehow we could get the emulator to accept plug ins such as the  SPU SYNC function on FPSE (which actually fixes the audio problems on MGS and other bunch of games) and the Frameskip Fix/Invert Colors (which fixes the crashing issues on MSG and the graphic bugging on Castlevania) those plug ins combined with the rendering function of the pref file could fix all or most of the compatibility issues.

Sorry I haven't found a way to do it but I'm still trying and I thought to share this with you being the expert on this emulator to see if this is really possible, let me know what you think.

**Comment by yifanlu** [comment]
Sorry, emulator related problems cannot be fixed by me, as Sony created the emulator. I can only deal with issues regarding the tool.
