### ISSUE TITLE
Emulator opens and closes after 2-3sec when converting with Windows

### ISSUE THREAD

**Issue by Hypfer** [yifanlu/PSXperia#2]
No error message given. It just closes

I'm using release 1 of the crash apk which was included in the rooted rom linked by yifanlu

**Comment by shotgunfool** [comment]
I have the exact same issue, you can see the playstation pocket app starting up and then it closes.

The led indicator at the top of the phone also flashes white when crashing too,

Tried a few games using different file formats iso bin img just to see if any would work but same issue every time.

EDIT*

Pc - Windows 7 32bit

Phone - Android 2.3.3 Unrooted Locked Bootloader

**Comment by yifanlu** [comment]
To those of you getting auto crash, please post what OS you're using. I get this on my windows machine, but not on my mac or linux machines.

**Comment by woogers** [comment]
Same error as these with the signed apk you sent back

Windows Vista x86.

**Comment by Hypfer** [comment]
Debian testing as well as ubuntu 10.10

**Comment by yifanlu** [comment]
Laberkopf, are you saying this issue also exists on debian and ubuntu?

**Comment by Hypfer** [comment]
Yep

**Comment by shotgunfool** [comment]
Pc - Windows 7 32bit

Phone - Android 2.3.3 Unrooted Locked Bootloader

For Issue Above.

**Comment by yifanlu** [comment]
This issue has been fixed because windows uses pathname seperator "\" while unix uses "/" If you're still getting this problem, open a new issue with a new description.
