### ISSUE TITLE
Extract and Convert tabs Disabled

### ISSUE THREAD

**Issue by uronacid** [yifanlu/PSXperia#22]
I've installed Java 6 JDK, however when I launch the PSXperiaTool.jar all of the tabs are disabled even after I accept the terms of use. 

I'm using Windows 7 64-bit

**Comment by yifanlu** [comment]
No you didn't. Please read more carefully ;)

**Comment by Goldensniper** [comment]
I have also the same problem... Information, Extract and Convert Tab stay disabled..
