### ISSUE TITLE
after APK crash, system deletes ZPAKs automatically

### ISSUE THREAD

**Issue by williedynamite** [yifanlu/PSXperia#23]
US crask APK with US MKTrilogy ISO

Trying to run Mortal Kombat Trilogy.  After moving the APK and data over to the device, I can install it with no problem.  When I go to run it I get an error stating "The content cannot be started.  You must download the content again"  At that point the zpak gets deleted automatically.   If I hit cancel on the error and try to run it again, I get "No content was found on the SD card.  Check the SD Card or download this content again".  I was able to get Resident Evil 3 to work fine.  Not sure what I'm missing.  The APK shows everything successful.  Here's the logcat of the run:

--------- beginning of /dev/log/system
I/ActivityManager(  180): Starting: Intent { act=android.intent.action.MAIN cat=
[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.sony.playstation.NCXA0
0330_1 cmp=com.sony.playstation.NCXA00330_1/com.sony.android.psone.BootActivity
} from pid 1511
--------- beginning of /dev/log/main
I/ZJavaActivity( 1541): onCreate
D/ZJavaActivity( 1541): library=/data/data/com.sony.playstation.NCXA00330_1/lib/
libjava-activity-wrapper.so
D/dalvikvm( 1541): Trying to load lib /data/data/com.sony.playstation.NCXA00330_
1/lib/libjava-activity-wrapper.so 0x2afc8910
D/dalvikvm( 1541): Added shared lib /data/data/com.sony.playstation.NCXA00330_1/
lib/libjava-activity-wrapper.so 0x2afc8910
I/ZJavaActivity( 1541): CreateContentView()
I/ZJavaActivity( 1541): MotionEvent has getSource()!
D/ZJavaActivity( 1541): sourceDir=/data/app/com.sony.playstation.NCXA00330_1-1.a
pk
D/ZJavaActivity( 1541): publicSourceDir=/data/app/com.sony.playstation.NCXA00330
_1-1.apk
D/ZJavaActivity( 1541): processName=com.sony.playstation.NCXA00330_1
D/ZJavaActivity( 1541): dataDir=/data/data/com.sony.playstation.NCXA00330_1
D/ZJavaActivity( 1541): PackageName=com.sony.playstation.NCXA00330_1
D/dalvikvm( 1541): Trying to load lib /data/data/com.sony.playstation.NCXA00330_
1/lib/libjava-activity.so 0x2afc8910
D/dalvikvm( 1541): Added shared lib /data/data/com.sony.playstation.NCXA00330_1/
lib/libjava-activity.so 0x2afc8910
I/ZJavaActivity( 1541): onGlobalLayout()
I/ZJavaActivity( 1541): surfaceCreated()
I/ZJavaActivity( 1541): surfaceChanged()
I/ZJavaActivity( 1541): onGlobalLayout()
I/ZJavaActivity( 1541): onGlobalLayout()
I/ActivityManager(  180): Displayed com.sony.playstation.NCXA00330_1/com.sony.an
droid.psone.BootActivity: +584ms
I/com.sonyericsson.semcsuite.app.PSSuiteActivity( 1511): onStop
I/com.sonyericsson.semcsuite.data.PackageDataSource( 1511): Dataset is invalidat
ed
D/dalvikvm( 1541): GC_CONCURRENT freed 1525K, 61% free 2685K/6791K, external 208
8K/2130K, paused 2ms+2ms
D/dalvikvm( 1541): GC_CONCURRENT freed 716K, 61% free 2685K/6791K, external 2088
K/2130K, paused 2ms+2ms
D/dalvikvm( 1541): GC_CONCURRENT freed 724K, 62% free 2635K/6791K, external 2088
K/2130K, paused 2ms+2ms
D/dalvikvm( 1541): GC_CONCURRENT freed 677K, 62% free 2636K/6791K, external 1682
K/2130K, paused 2ms+2ms
D/dalvikvm( 1541): GC_CONCURRENT freed 537K, 62% free 2631K/6791K, external 1682
K/2130K, paused 2ms+2ms
D/dalvikvm( 1541): GC_CONCURRENT freed 531K, 62% free 2643K/6791K, external 1682
K/2130K, paused 2ms+1ms
D/dalvikvm( 1541): GC_CONCURRENT freed 542K, 62% free 2631K/6791K, external 1682
K/2130K, paused 2ms+2ms
D/dalvikvm( 1541): GC_CONCURRENT freed 538K, 62% free 2621K/6791K, external 1682
K/2130K, paused 2ms+1ms
D/dalvikvm( 1541): GC_CONCURRENT freed 489K, 61% free 2648K/6791K, external 1682
K/2130K, paused 2ms+2ms
I/com.sonyericsson.semcsuite.data.PackageDataSource( 1511): Dataset has changed
I/com.sonyericsson.semcsuite.app.PSSuiteActivity( 1511): onRestart
I/com.sonyericsson.semcsuite.app.PSSuiteActivity( 1511): onStart()
I/com.sonyericsson.semcsuite.app.PSSuiteActivity( 1511): onResume
I/com.sonyericsson.semcsuite.data.PackageDataSource( 1511): Dataset has changed
I/com.sonyericsson.semcsuite.app.PSSuiteActivity( 1511): Fetched background sett
ings, mode: 2 index: 5 theme: 0
I/ZJavaActivity( 1541): surfaceDestroyed()
D/dalvikvm( 1511): GC_EXTERNAL_ALLOC freed 50K, 51% free 2746K/5575K, external 7
970K/8000K, paused 37ms
D/dalvikvm( 1511): GC_EXTERNAL_ALLOC freed 24K, 51% free 2738K/5575K, external 8
353K/8467K, paused 29ms
I/ActivityManager(  180): Process com.sony.playstation.NCXA00330_1 (pid 1541) ha
s died.
I/WindowManager(  180): WIN DEATH: Window{2b3e6b10 SurfaceView paused=false}
I/WindowManager(  180): WIN DEATH: Window{2b3e56e0 com.sony.playstation.NCXA0033
0_1/com.sony.android.psone.BootActivity paused=false}
W/ActivityManager(  180): Activity destroy timeout for HistoryRecord{2b366df8 co
m.sony.playstation.NCXA00330_1/com.sony.android.psone.BootActivity}

**Comment by williedynamite** [comment]
went back in and re-extracted and created the APK from scratch.  Tried installing through ADB and adb shows successful but the device gives a force close error.  zpak and toc get deleted.

**Comment by yifanlu** [comment]
Are you sure you're copying to the right directory? It's on the sdcard under Anderoid/data

**Comment by rikd88** [comment]
.

**Comment by yifanlu** [comment]
Tell me if this is still an issue. I cannot reproduce it and nobody else has commented on it.

**Comment by rikd88** [comment]
hi sorry for delay getting back to you, i have tried again but still get the same problem??? how do i get the osi file? is it the file from a rom? im trying to go bk 2 the start as not sure what the problem is?? thanks alot!!!
