### ISSUE TITLE
Broken Games

### ISSUE THREAD

**Issue by Atlas51** [yifanlu/PSXperia#25]
1 - Castlevania Symphony of the Night (USA) (Broken)
2 - Castlevania Chronicles (USA) (Broken)
3 - Ninja Shadow of Darkness (USA) (After Finish First Stage it's Not Work)
4 - Tenchu Stealth Assassins (USA) (Playable But Has Some Glitches)
5 - Tenchu 2 Birth of the Stealth Assassins (USA) (Playable But Has Some Glitches)
6 - Crash Bash (USA) (Playable But Has Some Glitches)
7 - Vigilante 8 (USA) (Broken)
8 - Vigilante 8 2nd (USA) (Broken)
9 - Theme Park (USA) (Broken)
10 - Sim Theme Park (USA) (Broken)
11 - 40 Winks (USA) (Playable But Has Some Glitches)
12 - Mortal Kombat Trilogy (USA) (Playable But Has Some Glitches)
13 - Tomba! (USA) (Playable But Sometimes Its Work Slow)
I Converted All These Games By Crash Bandicoot (USA)

**Comment by yifanlu** [comment]
As I stated before, I cannot fix game problems. Tell Sony to make a better emulator.
