### ISSUE TITLE
Analogue pad support

### ISSUE THREAD

**Issue by ghost** [yifanlu/PSXperia#26]
I've tried a number of analogue controller supported games (e.g. Driver 2, Gran Turismo 2, Need for speed III etc.) I've ticked the analogue mode in the GUI and selected control type 5 or 6 when in the game, but the analogue pads are non functioning, but the rest of the keys are fine. However, in Crash Bandicoot 3, the analogue mode works perfectly. 

Edit: Apologies for my misunderstanding, I presumed it was to do with repacking the games in this manner not necessarily the emulator itself, sorry,

**Comment by yifanlu** [comment]
As I've stated in many other issues, I cannot fix emulator problems, only the tool. You need Sony to do that.
