### ISSUE TITLE
FF7 You wont able to end it.

### ISSUE THREAD

**Issue by Kroktar** [yifanlu/PSXperia#30]
I have been playing a lot FF7 and it works amazing in PSXPERIA but there are many issues when you advance in the game

The issues are with the "cutscenes" or videos, they will get glitched and stuck...i have tried many times...
The one wich i remember a lot is when you end the story of XII and there is a video of his father...it will crash and you wont be able to advance.

Sound is way better than FPSE but FPSE is the only option to advance in the game. unless you want to save and change to FPSE until you end the video.

**Comment by yifanlu** [comment]
Unfortunately, only Sony can fix issues with the emulator.

**Comment by danaiudo** [comment]
I have no problem for FF7 and I finished FF7 already.
