### ISSUE TITLE
Extract Error "This APK is not a known valid one.. CRC32: 1759874476"

### ISSUE THREAD

**Issue by Hayzenciell** [yifanlu/PSXperia#32]
I got this "This APK is not a known valid one. The extractor will continue but you may get errors later on. CRC32: 1759874476" error message when extracting US Crash APK and ZPAK copied from my phone & SD.( http://i56.tinypic.com/16k5rw4.png ) 

then the extraction went and finished. I tried making Harvest Moon APK (with the ISO that works in my PC emulator) added random string and icon image. installed it on my phone. the game just shuts down after the "updating.."  screen.

**Comment by yifanlu** [comment]
That APK is not supported. You need to obtain a supported APK. Look around, I cannot provide it for legal reasons.
