### ISSUE TITLE
issue creating parappa the rapper apk

### ISSUE THREAD

**Issue by soratheultima** [yifanlu/PSXperia#35]
im trying to make a parappa the rapper apk from the original USA disc i own  _i already tried crash bandicoot 3 warped and it worked_   but it gives me this... Cannot Build APK! Java says: Executable did not return without error

**Comment by yifanlu** [comment]
Can you follow the troubleshooting guide found in the wiki?

**Comment by soratheultima** [comment]
yes i did everything and read everything yet still nothing it worked perfectly fine with crash 3 warped

**Comment by yifanlu** [comment]
Please provide the log output. You can reopen the ticket once you have the log.
