### ISSUE TITLE
problem with psxperia tool

### ISSUE THREAD

**Issue by scorpion2710** [yifanlu/PSXperia#36]
Hello,

I have a problem with this tool.
When i want convert a iso in apk file, i can't push on the "OK" boutton because he is hidden by the windows.

NB: I have Windows XP  PENTIUM 4 .

Thanks for your answer.

**Comment by FrPeeweeStairmaster** [comment]
Have you got the latest version of Java from here:
http://java.com/en/download/index.jsp

**Comment by scorpion2710** [comment]
Hello Drunkenfcuk,

Yes I have the latest version of Java.
