### ISSUE TITLE
Rip format advised: MDF, BIN, IMG, ISO. What about SUB?  

### ISSUE THREAD

**Issue by fibriZo** [yifanlu/PSXperia#37]
Hi there ^__^,

First of all, thank you very much for your research; you're doing a great job ;)

I only have a little doubt: do you recommend using a specific rip format for optimum performance of your converter tool? I guess MDF is not supported because I tried it with Tekken3 and it didn't run...

And what should I do with the extension SUB? Is it necessary? Should I convert SUB + IMG into ISO before using the tool?

Thanks in advance.
Regards,

fibriZo

**Comment by yifanlu** [comment]
SUB is not supported. You need a valid PSX image format. It's commonly extensioned .img, .bin, or .iso.
