### ISSUE TITLE
Support for .bin files

### ISSUE THREAD

**Issue by iluvdurians** [yifanlu/PSXperia#39]
I have a .cue and .bin version of final fantasy tactics which works fine in the epsxe emulator. However, I see the "updating" sign flash across after installing and loading the game and then it brings me back to the homescreen. Supposedly FFTactics is a supported game?

I'm currently using the com.sony.plasytation.ncua94900_1.apk and the NCUA9000_1_.zpak. I've tried using the defaults and I get the results above. I am running an r800a that's still on 2.3.2.

**Comment by yifanlu** [comment]
I need more information. Log files and such. You can reopen the ticket after providing some logs.
