### ISSUE TITLE
Converter does not work with "release 1" CB Europe APK

### ISSUE THREAD

**Issue by yifanlu** [yifanlu/PSXperia#4]
Although the file name is the same, there are at least two versions of the Europe version of the Crash Bandicoot APK. The one with a CRC32 value of BB542581 is called "release 2" and is tested working. If you have a APK with the name "com.sony.playstation.ncea00344_1.apk", but with a different CRC32, please post that number.

**Comment by yifanlu** [comment]
This is the CRC32 of the "non-working" one: 3B6A23C1

**Comment by Hypfer** [comment]
Yep i can confirm that Crc32

**Comment by kingvillain** [comment]
I also have the CRC32 3b6a23c1, not working

**Comment by yifanlu** [comment]
New version blocks "release 1" apks, so you won't have to wait until you upload to the phone to find it not working.

**Comment by Levistras** [comment]
Also doesn't work with Canadian release, CRC32 E7BCB6D5.

**Comment by yifanlu** [comment]
It does, in fact work with E7BCB6D5, because that is the same as the USA one. Your issue must be something different.

**Comment by Levistras** [comment]
That it does, got it working after I freshly downloaded the zpak to the phone from sony, ripped it off, extracted it again with your tool.. And now I can finally make packages that work.  

------Original Message------

**Comment by Nextria** [comment]
I know now, i reinstalled everything and now it works :).
Also i downloaded JDK 6 instead of 7.

tnx anyway

**Comment by username33** [comment]
So if I have the com.sony.playstation.ncea00344_1.apk file, it wont work at all?

**Comment by yifanlu** [comment]
If ta crc32 value is the one I said won't work.

**Comment by h0m3r** [comment]
Unsupported exception: This version of Crash Bandicoot is known to not work, please use a different version. CRC32: 996811713

**Comment by yifanlu** [comment]
Yes, that is the very APK I was talking about.

**Comment by h0m3r** [comment]
Any clue where from I can get that different version?

**Comment by Kousa** [comment]
Unfortunately my Europe version didn't work,could you give me direction to find the version number?cause I don't know it is 3B6A23C1 or sth else,thank ya

**Comment by Tech7** [comment]
everytime when i try to extract the files from the crash bandicoot files from xperia play (the apk and the zpk file) it gives me this error:

"Unsuported Expection: This Version of Crash Bandicoot﻿ is known to not work, please use a different version. CRC32 996811713"

I tried copy the﻿ files from the phone to the desktop but I get the same error

What I did:
I grabbed the apk from here http://forum.xda-developers.com/show....php?t=1220725 and used my existing .zapk and i could extract and convert

yifanlu will be any problem if a try to run the converted output this way ? I mean with the crash bandicoot stock installed not compatible with the PSXperia?

Thanks in advance

**Comment by yifanlu** [comment]
It's fine.

**Comment by Tech7** [comment]
Thanks a lot :) 
RR4 plays much better in therms of sound then FPse and with SW rendering is even better

**Comment by yifanlu** [comment]
This APK is now outdated and would be useless to support. Closing ticket.
