### ISSUE TITLE
Cannot build apk. Java says: Cannot create temporary directory!

### ISSUE THREAD

**Issue by Trueheartless** [yifanlu/PSXperia#41]
Not sure how to resolve this issue, I've checked previous issue threads and google searched for a while but couldn't find anything. This occurs after I try to convert the iso, it happens with each of the four isos I have so I was unsure as to whether it was that I'm really unlucky or I'm doing something wrong or what.

**Comment by yifanlu** [comment]
You need write permissions on the folder where PSXPeria is located

**Comment by Trueheartless** [comment]
Already has write permissions

**Comment by wouter2** [comment]
i have the same problem

**Comment by psxpetey** [comment]
Did u try runnin as administrator
