### ISSUE TITLE
NCOA verson not compatible. 

### ISSUE THREAD

**Issue by Evzy** [yifanlu/PSXperia#45]
CRC32: FAF1B65A. the error i get is as follows when trying to extract the APK. 

 Cannot extract APK! Java says Cannot find config for this APK (CRC32: FAF1B65A)

Do you need my APK file to patch?

**Comment by yifanlu** [comment]
Yes, I've said it before, if I don't have the APK, there's nothing I can do about it.

**Comment by Evzy** [comment]
do you want my apk? what should you do

**Comment by Evzy** [comment]
I\* sorry

**Comment by Evzy** [comment]
Dont worry, im getting the US apk to download the ZPAK file. if you ever need that APK to patch for PSXperia 2.0, let me know

**Comment by yifanlu** [comment]
Yes, send me the APK anyways so others won't have the problem.
