### ISSUE TITLE
How to get CDDA audio tracks working

### ISSUE THREAD

**Issue by RobertoTorino** [yifanlu/PSXperia#46]
Some games use separate CDDA audio tracks for the in-game music, at the moment those games have no music using this converter (2.0 Beta). Is there a method to get those CDDA tracks working?
Example: Ridge Racer, Tekken.

**Comment by yifanlu** [comment]
In-game problems cannot be fixed by me, only Sony. Sorry.

**Comment by RobertoTorino** [comment]
It's not a game issue but a converting issue, just like converting for PSX classics for the PSP. Because some games where released on multimode cd's. They contain 1 data track and multiple audio tracks. The official Wipeout classic in the Android market is a great example that it can be done. This game was also released as a multimode cd.

**Comment by Danixu** [comment]
Maybe is a emulator problem and maybe a converter problem, i know that in PSP if you use a normal converter then CDDA tracks don't works but if you use a special converter that add track info to file then CDDA tracks works fine.

**Comment by RobertoTorino** [comment]
The track information has to be included in the converted game, this can be done by adding the track information from the cue file to the toc file. It allows control over track/index positions, pre-gaps and sub-channel information.
For the popsconverter (PSP) this was done by Tinnus who recompiled it and added the CDDA fix aka TOC Converter.
This information is ignored in the current converter that's why those CDDA tracks don't work.
