### ISSUE TITLE
Converter crashes at end when "aapt" or "jarsigner" is not found

### ISSUE THREAD

**Issue by yifanlu** [yifanlu/PSXperia#5]
You need to have Android SDK and Java JDK installed and their "bin" folders in your system's PATH variable. Open a new command prompt/terminal window and type in "aapt" and then "jarsigner", and if they error or complain about not being found, you did not do this. I hope I can lose this dependency by the release.

**Comment by Levistras** [comment]
I had an instance where aapt and jarsigner were both in the path but I still got this error.  I had to manually run the jarsigner command (copy and paste from console output to another command prompt) and was able to sign the apk just fine.
