### ISSUE TITLE
Cannot get any games to work - updating, then return to menu

### ISSUE THREAD

**Issue by philh99** [yifanlu/PSXperia#55]
I have a couple of .img files I have ripped which all run on Psxdroid, so I am sure the images are good.

I have extracted everything, including the last update of Crash, after the 2.3.4 update.

I have left everything on default this time and converted Grand Tourismo 2 - Arcade disk, which is said to be working on the compatibility list.  I have then copied files to my phone, but they show the updating... screen briefly, then return to the previous menu.  I have tried to run without the SD Card in to confirm it is looking for the data on the SD Card and I do receive the message that the SD Card is not present, so I am happy everything is setup and copied to the correct place, as per the instructions.

I do not receive any errors or messages while running the program.

Here are the contents of the psxperia.log file:

[I] PSXperiaTool initialized, outputting to: H:\stuff\Phone\PSXPERIA.\output
[I] Starting build with PSXPeria Converter version 2.0 Beta
[I] Checking to make sure all files are there.
[I] Using data from Crash Bandicoot EUR Version 1.0.3, CRC32: 7C33475B
[D] Done checking data.
[I] Creating temporary directory.
[D] Created temporary directory at, ..psxperia.648
[I] Copying icon if needed.
[I] Replacing strings.
[D] Replacing strings in XML data.
[D] Writing to temporary file: ..psxperia.648\assets\AndroidManifest.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.648\assets\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.648\res\values\strings.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.648\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Done with string replacement.
[D] Done replacing strings.
[I] Patching game.
[I] Making a copy of game.
[D] Done patching game.
[I] Generating PSImage.
[I] Beginning PSImage compression.
[I] Generating image TOC.
[D] Done generating PSImage
[D] Deleting temporary patched game.
[I] Generating ZPAK.
[I] Generating zpak file from directory ..psxperia.648\ZPAK with compression = false
[D] Done with ZPAK creation.
[D] Done generating ZPAK at ..psxperia.648\NCXA00000_1.zpak
[I] Generating default ZPAK.
[I] Generating zpak file from directory ..psxperia.648\assets\ZPAK with compression = true
[D] Done with ZPAK creation.
[D] Done generating default ZPAK at ..psxperia.648\assets\NCXA00000_1.zpak
[I] Done processing, generating output.
[D] Moving files around.
[D] Running command: [.\aapt-windows.exe package -f -F H:\stuff\Phone\PSXPERIA.\output\com.sony.playstation.NCXA00000_1.apk.unsigned -S ..psxperia.648\res -M ..psxperia.648\assets\AndroidManifest.xml -I .\android-framework.jar ..psxperia.648]
[I] Signing apk H:\stuff\Phone\PSXPERIA.\output\com.sony.playstation.NCXA00000_1.apk.unsigned to H:\stuff\Phone\PSXPERIA.\output\com.sony.playstation.NCXA00000_1.apk
[I] Done.
[I] APK file: H:\stuff\Phone\PSXPERIA.\output\com.sony.playstation.NCXA00000_1.apk
[I] Data dir: H:\stuff\Phone\PSXPERIA.\output\data\com.sony.playstation.NCXA00000_1\files\content
[I] Deleting temporary directory
[I] Done.
.

NCXA00000_1

WinXP - 32bit, but also tried Win7 - 32 bit

**Comment by HussainQ** [comment]
The .img files should all actually be .bin files to convert (that's how it works for me)

**Comment by philh99** [comment]
It does say they should be image files, which I take to be either .img, .bin or .iso.  The program doesn't complain about the image file, it does extract.

**Comment by HussainQ** [comment]
Oh I see what you've done wrong. The .apk and .zpak you need is the USA one not the EUR!!!

**Comment by philh99** [comment]
Thanks, I have been on the xda developers forum and seen this.  I have just downloaded the data.rar from one particular thread and I have successfully converted my first game and it does play.  Colin McRae Rally.  Thank you very much for the replies

**Comment by philh99** [comment]
And, of course, thank you so much for a great program.
