### ISSUE TITLE
Convert ISO from Syphon Filter apk / zapk

### ISSUE THREAD

**Issue by seuf** [yifanlu/PSXperia#65]
Hi,

I have a french xperia play and unfortunatly, the free game delivered with the phone is not crash bandicoot, it's Syphon Filter.
Do you think it's possible to add support for converting iso based on this apk, zapk ?
I can send you my .apk and zapk files if you want..

I've already tried to use this files but PSXPeria-2.0-beta say : "Cannot build APK ! Java says : cannot find list to validate files"

Thierry.

**Comment by HussainQ** [comment]
Send me the files. I think I can fix that for you.

**Comment by seuf** [comment]
OK, i sent you the files in private message...

**Comment by HussainQ** [comment]
Check your private messages inbox.

**Comment by Physix-zz** [comment]
Send Me Too

**Comment by Physix-zz** [comment]
Try Download Crash Bandicoot Apk. and zpak.
