### ISSUE TITLE
Icons Not Working when trying to build apk

### ISSUE THREAD

**Issue by shotgunfool** [yifanlu/PSXperia#8]
When trying to build an apk i cant use any icon otherwise i get an error

cannot build apk

the picture im using the details are;

Dimensions 170x170pixels
Bit Depth 24
Item type PNG Image
Size 14.3kb

Any Ideas?

**Comment by yifanlu** [comment]
Can you attach the icon you're trying to use. The icons I've used all works.

**Comment by shotgunfool** [comment]
https://rapidshare.com/files/1620585423/fifa1.png

**Comment by kingvillain** [comment]
My icon worked just fine, it was a 170x170 png

**Comment by yifanlu** [comment]
Here's your problem. It's not a "real" png file. PNGs file have a magic number of "89504E47", or ".PNG" as the first four bytes of the header. Your file is "FFD8FFE0", or a JPEG renamed to PNG. You need to either convert it to PNG or something.
