### ISSUE TITLE
Games do not start

### ISSUE THREAD

**Issue by Eneas64** [yifanlu/PSXperia#86]
I converted an European PS1 (Rayman) in Version 1.0 and 2.0 and the extracting and building finished without any errors and the installation of the apk file too but when I try to start the game, I see for a second a black screen und then I get kicked back into the playstation pocket app. I also tried it also with other games but every time I get the same results.

**Comment by severn2** [comment]
Could you attach the log for your conversion?

I am not sure if this tools conversion is a requirement for you, but (in my opinion) it was easier for me to install epsxe for Android gingerbread and emulate my games using that.
