### ISSUE TITLE
Emulator crashes after launch

### ISSUE THREAD

**Issue by ChrisKenison** [yifanlu/PSXperia#9]
Converter output:
[I] Verifying files
[I] Decoding values
Aug 11, 2011 3:03:39 PM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loading resource table...
Aug 11, 2011 3:03:39 PM brut.androlib.res.AndrolibResources loadMainPkg
INFO: Loaded.
Aug 11, 2011 3:03:39 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
INFO: Loading resource table from file: C:\Documents and Settings\ca2432\apktool
\framework\1.apk
Aug 11, 2011 3:03:41 PM brut.androlib.res.AndrolibResources loadFrameworkPkg
INFO: Loaded.
Aug 11, 2011 3:03:41 PM brut.androlib.res.AndrolibResources decode
INFO: Decoding file-resources...
Aug 11, 2011 3:03:41 PM brut.androlib.res.AndrolibResources decode
INFO: Decoding values_/_ XMLs...
Aug 11, 2011 3:03:41 PM brut.androlib.res.AndrolibResources decode
INFO: Done.
[I] Extracting APK
[I] Extracting ZIP file: C:\Documents and Settings\ca2432\My Documents\psxperiat
ool-beta-2\Crash\com.sony.playstation.ncua94900_1.apk to: C:\Documents and Setti
ngs\ca2432\My Documents\psxperiatool-beta-2.\data
[D] Done extracting ZIP.
[I] Extracting ZPAKS
[I] Extracting ZIP file: C:\Documents and Settings\ca2432\My Documents\psxperiat
ool-beta-2.\data\assets\NCUA94900_1_1.zpak to: C:\Documents and Settings\ca2432
\My Documents\psxperiatool-beta-2.\data\assets\ZPAK
[D] Done extracting ZIP.
[I] Extracting ZIP file: C:\Documents and Settings\ca2432\My Documents\psxperiat
ool-beta-2\Crash\NCUA94900_1_1.zpak to: C:\Documents and Settings\ca2432\My Docu
ments\psxperiatool-beta-2.\data\ZPAK
[D] Done extracting ZIP.
[I] Removing unneeded files.
[I] Adding new files.
[I] Patching XML strings with tags.
[D] Replacing strings in XML data.
[D] Writing to temporary file: C:\Documents and Settings\ca2432\My Documents\psx
periatool-beta-2.\data\assets\AndroidManifest.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: C:\Documents and Settings\ca2432\My Documents\psx
periatool-beta-2.\data\assets\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: C:\Documents and Settings\ca2432\My Documents\psx
periatool-beta-2.\data\res\values\strings.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: C:\Documents and Settings\ca2432\My Documents\psx
periatool-beta-2.\data\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Done with string replacement.
[I] Done.
[I] PSXperiaTool initialized, outputting to: C:\Documents and Settings\ca2432\My
 Documents\psxperiatool-beta-2\output
[I] Starting build.
[I] Checking to make sure all files are there.
[D] Done checking data.
[I] Creating temporary directory.
[D] Created temporary directory at, ..psxperia.857
[I] Copying icon if needed.
[I] Replacing strings.
[D] Replacing strings in XML data.
[D] Writing to temporary file: ..psxperia.857\assets\AndroidManifest.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.857\assets\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.857\res\values\strings.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Writing to temporary file: ..psxperia.857\ZPAK\metadata.xml.tmp
[D] Successfully cleaned up and done with string replacement.
[D] Done with string replacement.
[D] Done replacing strings.
[I] Generating PSImage.
[I] Beginning PSImage compression.
[I] Generating image TOC.
[D] Done generating PSImage
[I] Generating ZPAK.
[I] Generating zpak file from directory ..psxperia.857\ZPAK with compression =
false
[D] Done with ZPAK creation.
[D] Done generating ZPAK at ..psxperia.857\NCXA00000_1.zpak
[I] Generating default ZPAK.
[I] Generating zpak file from directory ..psxperia.857\assets\ZPAK with compres
sion = true
[D] Done with ZPAK creation.
[D] Done generating default ZPAK at ..psxperia.857\assets\NCXA00000_1.zpak
[I] Done processing, generating output.
[D] Moving files around.
[D] Running command: [.\aapt-windows.exe package -f -F C:\Documents and Settings
\ca2432\My Documents\psxperiatool-beta-2\output\com.sony.playstation.NCXA00000_1
.apk.unsigned -S ..psxperia.857\res -M ..psxperia.857\assets\AndroidManifest.x
ml -I .\android-framework.jar ..psxperia.857]
[I] Signing apk C:\Documents and Settings\ca2432\My Documents\psxperiatool-beta-
2\output\com.sony.playstation.NCXA00000_1.apk.unsigned to C:\Documents and Setti
ngs\ca2432\My Documents\psxperiatool-beta-2\output\com.sony.playstation.NCXA0000
0_1.apk
[I] Done.
[I] APK file: C:\Documents and Settings\ca2432\My Documents\psxperiatool-beta-2\
output\com.sony.playstation.NCXA00000_1.apk
[I] Data dir: C:\Documents and Settings\ca2432\My Documents\psxperiatool-beta-2\
output\data\com.sony.playstation.NCXA00000_1\files\content
[I] Deleting temporary directory
[I] Done.

Not sure how to get logcat info...

**Comment by ChrisKenison** [comment]
Also, I used default info on the Convert tab. No Images used.

**Comment by yifanlu** [comment]
Can you send me the APK that you generated? To get logcat, enable debugging on your phone, and with the android sdk, run "adb logcat"

**Comment by ChrisKenison** [comment]
Okay, it's working now. I don't have a clue what I did, but when I tried to load it, it started to work! :P
